meshID: paas-mesh
multiCluster:
  clusterName: security
network: security-network

resources: 
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

ingressGateways:
  eastwestgatewayEnabled: true
  ingressgatewayEnabled: true
