apiVersion: v1
kind: Secret
metadata:
  name: cacerts
  annotations:
    # avp.kubernetes.io/path: "paas2/k8s/bwb-dev/certs/ca-cert.pem"
    avp.kubernetes.io/path: "paas2/k8s/bwb-dev"
type: Opaque
stringData:
  # password: <pem>
stringData:
  ca-cert.pem: |
    <certs/ca-cert.pem | jsonPath {.pem}>
