apiVersion: v1
kind: Secret
metadata:
  name: cacerts-delete
  annotations:
    avp.kubernetes.io/path: sahap2-kv/data/bwb-dev/cacerts
    # avp.kubernetes.io/kv-version: 2
type: Opaque
stringData:
  east-cluster: |
    apiVersion: v1
    kind: Config
    preferences: {}
    clusters:
    - cluster:
        ca-cert.pem: <ca-cert>
        server: <server>
      name: security-cluster
    users:
    - name: security-cluster
      user:
        token: <sa-token>
    contexts:
    - context:
        cluster: security-cluster
        user: security-cluster
      name: security-cluster
    current-context: security-cluster     