{{- if .Values.configs.secret.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: cacerts
type: Opaque
data:
  webhook.github.secret: {{ .Values.configs.secret.githubSecret | b64enc }}
  webhook.gitlab.secret: {{ .Values.configs.secret.gitlabSecret | b64enc }}
  webhook.bitbucketserver.secret: {{ .Values.configs.secret.bitbucketServerSecret | b64enc }}
  webhook.bitbucket.uuid: {{ .Values.configs.secret.bitbucketUUID | b64enc }}
  webhook.gogs.secret: {{ .Values.configs.secret.gogsSecret | b64enc }}
