apiVersion: v1
kind: Secret
metadata:
  annotations:
    networking.istio.io/cluster: security
    avp.kubernetes.io/path: sahab2-kv/data/shared/{{ .Values.global.clusterName }}-{{ .Values.global.env}}    
  labels:
    istio/multiCluster: "true"
  name: security-cluster-remote-secret
  namespace: istio-system
stringData:
  security-cluster: |
    apiVersion: v1
    kind: Config
    preferences: {}
    clusters:
    - cluster:
        certificate-authority-data: <certificate-authority-data>
        server: <server>
      name: security-cluster
    users:
    - name: security-cluster
      user:
        token: <sa-token>
    contexts:
    - context:
        cluster: security-cluster
        user: security-cluster
      name: security-cluster
    current-context: security-cluster