apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  ports:
  - name: http
    port: 8200
    protocol: TCP
    targetPort: 8200
  selector:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    component: server