apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: argocd
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: http-443
      protocol: HTTP
    hosts:
    - "*"      
  - port:
      number: 80
      name: http-80
      protocol: HTTP      
    hosts:
    - "*"

