apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd
spec:
  hosts:
  - "*"
  gateways:
  - argocd
  http:
  - name: "argocd-v1"
    route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
        port:
          number: 443        
        # subset: v2  
  # http:
  # - match:
  #   - uri:
  #       exact: /vault
  #   route:
  #   - destination:
  #       host: helm-vault.vault.svc.cluster.local
  #       port:
  #         number: 8200                   