apiVersion: v1
kind: Secret
metadata:
  annotations:
    networking.istio.io/cluster: security
  labels:
    istio/multiCluster: "true"
  name: istio-remote-secret-security-cluster
  namespace: istio-system
stringData:
  east-cluster: |
    apiVersion: v1
    kind: Config
    preferences: {}
    clusters:
    - cluster:
        certificate-authority-data: <omitted>
        server: https://east-clust-dkjqiu.hcp.eastus.azmk8s.io:443
      name: security-cluster
    users:
    - name: security-cluster
      user:
        token: <omitted>
    contexts:
    - context:
        cluster: security-cluster
        user: security-cluster
      name: security-cluster
    current-context: security-cluster